
// Export all proc macros.
pub use bunt_macro::{write, writeln, print, println, style};

// Reexport of `termcolor`. This is mostly to be used by the code generated by
// the macros.
pub extern crate termcolor;
